# Generated by Django 2.1.5 on 2019-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='creds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
