# Generated by Django 2.1.5 on 2019-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('sap', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('issued', models.IntegerField()),
                ('issuem', models.IntegerField()),
            ],
        ),
    ]
